### ISSUE TITLE
Gob "Barque" invalide

### ISSUE THREAD

**Issue by Lurivar** [RussianBias/Brikabrok#1]
Le dernier gob de la liste de la 1.0.0 (Barque, dans la section "DE TERRE") est invalide. Probablement un typo dans l'ID. Celui envoyé est le 36812 qui ne correspond à aucun gob.

**Comment by YetAnotherBinarySpace** [comment]
L'entrée sera supprimée dans la prochaine mise à jour. Comme dit dans le post forum, ces "listes" ne sont que des placeholders fait par des contributeurs de l'addon et sont sujettes à remplacement.
Je maintiendrai celle-ci dans une moindre mesure, mais faire des listes "correctes", complètes et polyvalentes est un travail colossal pour une seule personne, donc n'hésitez pas à contribuer. Il me faudra juste le code sérialisé de vos créations afin de les intégrer ( cf wiki ).
